### PR TITLE
add a simple pixel tester

### PR DESCRIPTION
**Pull request by titimoby**
I propose this very simple arbapp.
It is useful to check that everything is soldered and properly configured.

### CODE REVIEW

**Comment by ymollard** [comment]
Why not using self.width and self.height instead of passing --nbstrips and --nbleds in argument? These informations are already known thanks to the config file.
Also I suggest using the with statement to lock/unlock the model since it is safer in case an exception is raised while the model is locked. See an example [here](https://github.com/arbalet-project/arbapps/blob/master/ColorDemonstrator/Colordemonstrator.py#L126-L134) (all old `model.lock()` and  `model.unlock()` calls in arbapps/\* should be switched to the with statement).

**Comment by titimoby** [comment]
The idea with --nbstrips and --nbleds in arguments is to be able to run several tests on only a part of the table.
The full idea is to allow to define the origin of the first pixel.
If I use configuration information, I will have to modify the Json each time.

**Comment by ymollard** [comment]
Ok, maybe check at least than the given values are inside the range [0, width] and [0, height] and display a meaningful info otherwise. Because any larger value won't bring any useful debug information, it will just cause the Arbalink thread to crash. Also think to change the PR for the `with` statement ;)

An advice: ipython notebooks are ideal to debug stuff, it is much faster and lighter than developing a dedicated Arbapp while debugging that you need to execute, kill, change, re-execute ... And the SDK is compatible with interactive python, see [the first tuto](https://github.com/arbalet-project/arbadoc/blob/master/notebooks/en/1.getting_started.ipynb).

**Comment by titimoby** [comment]
I pushed the code using With and existing Json parameters.
I wasn't a good contributor and forgot to use a dedicated branch before pulling my PR.
there will be 2 commits: to you want to close this PR and let me do a proper and cleaner history ?

**Comment by ymollard** [comment]
You ended up removing the parameters --nbstrips and --nbleds? I was just suggesting a check that they are lower to the configuration values ;)

No worries for the branch, there is no dev branch at the moment :)

**Comment by titimoby** [comment]
yes, I removed the 2 parameters, your suggestion was right and I'll see later if I need something else.
hope to hardware test it soon.

**Pull request merged**
